# Generated by Django 2.2.8 on 2020-04-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
                ('product_id', models.IntegerField()),
                ('product_picture', models.ImageField(default='no-img.png', upload_to='items/')),
                ('product_description', models.TextField(blank=True, help_text='Dwse mia perigrafi tou proiontos', max_length=300)),
            ],
        ),
    ]
