# Generated by Django 2.2.8 on 2020-04-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AlterField(
            model_name='item',
            name='product_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
