# Generated by Django 2.2.8 on 2020-04-07 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200406_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_review', models.TextField(blank=True, help_text='Dwse th gnwmmh sou gia to proion', max_length=300)),
                ('pub_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_rating', models.IntegerField(choices=[(1, 'ΔΕΝ ΜΟΥ ΑΡΕΣΕ ΚΑΘΟΛΟΥ'), (2, 'ΔΕΝ ΜΟΥ ΑΡΕΣΕ'), (3, 'ΜΕΤΡΙΟ'), (4, 'ΚΑΛΟ'), (5, 'ΤΕΛΕΙΟ')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
            ],
        ),
    ]
