# Generated by Django 2.2.8 on 2020-04-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200407_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemratings',
            name='product_rating',
            field=models.IntegerField(choices=[(1, 'ΔΕΝ ΜΟΥ ΑΡΕΣΕ ΚΑΘΟΛΟΥ'), (2, 'ΔΕΝ ΜΟΥ ΑΡΕΣΕ'), (3, 'ΜΕΤΡΙΟ'), (4, 'ΚΑΛΟ'), (5, 'ΤΕΛΕΙΟ')]),
        ),
    ]
