# Generated by Django 2.2.8 on 2020-04-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200407_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
