# Generated by Django 2.2.8 on 2020-04-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_item_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_category',
            field=models.IntegerField(choices=[(1, 'ΦΡΟΥΤΑ'), (2, 'ΛΑΧΑΝΙΚΑ'), (3, 'VEGGIESTREET')], default=1),
        ),
    ]
